name: Generate Reminder ICS

on:
  schedule:
    - cron: '0 22 * * *'  # 台灣時間 06:00（UTC+8）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ICS module
        run: pip install ics

      - name: Generate reminder.ics
        run: |
          mkdir -p public
          python3 generate_reminder.py  # 調用 Python 腳本來生成 reminder.ics

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
