name: Daily Reminders with Randomized Tone

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0,1,3,4,5'
    - cron: '0 0 * * 2,6'
    - cron: '0 12 * * *'
    - cron: '45 10 * * 0,1,3,4,5'
    - cron: '30 1 * * 2,6'

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python3 -m pip install openai

      - name: Create mock sleep data
        run: |
          mkdir -p processed
          echo '{
            "date": "2025-04-20",
            "sleep_summary": {
              "deep": 12300,
              "light": 22920,
              "rem": 7260,
              "awake": 12360,
              "total_sleep": 54840
            }
          }' > processed/mock_sleep.json

      - name: Generate randomized reminder
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cat <<EOF > script.py
import os, json, glob
from datetime import datetime

files = sorted(glob.glob('processed/*.json'), key=os.path.getmtime, reverse=True)
latest = files[0] if files else None

tone_type = ''
if latest:
    with open(latest, 'r', encoding='utf-8') as f:
        data = json.load(f)
    total = data.get('sleep_summary', {}).get('total_sleep', 0)
    if total >= 25200:
        tone_type = 'gentle'
    elif total >= 18000:
        tone_type = 'neutral'
    else:
        tone_type = 'concerned'

print('語氣分類為：' + tone_type)
EOF
  python3 script.py
