name: Minimal Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Write & Run Python
        run: |
          echo 'print("✅ 成功執行 Python")' > test.py
          python3 test.py
