name: Minimal Python Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test Python script
        run: |
          cat <<EOF > test.py
print("✅ Python 腳本成功執行")
EOF
          python3 test.py
