name: Daily Reminders with Randomized Tone

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0,1,3,4,5'
    - cron: '0 0 * * 2,6'
    - cron: '0 12 * * *'
    - cron: '45 10 * * 0,1,3,4,5'
    - cron: '30 1 * * 2,6'

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python3 -m pip install openai

      - name: Create mock sleep data
        run: |
          mkdir -p processed
          echo '{
            "date": "2025-04-20",
            "sleep_summary": {
              "deep": 12300,
              "light": 22920,
              "rem": 7260,
              "awake": 12360,
              "total_sleep": 54840
            }
          }' > processed/mock_sleep.json

      - name: Generate randomized reminder
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cat <<EOF > script.py
          import os, json, glob
          from datetime import datetime

                    files = sorted(glob.glob('processed/*.json'), key=os.path.getmtime, reverse=True)
          latest = files[0] if files else None

          tone_type = ''
if latest:
    with open(latest, 'r', encoding='utf-8') as f:
        data = json.load(f)
              total = data.get('sleep_summary', {}).get('total_sleep', 0)
    if total >= 25200:
        tone_type = 'gentle'
    elif total >= 18000:
        tone_type = 'neutral'
    else:
        tone_type = 'concerned'

          print('語氣分類為：' + tone_type)

          # 根據時間判斷提醒項目
                              now = datetime.utcnow().strftime('%H:%M')
          if now in ['23:00', '00:00', '12:00']:
              task = 'brush'
          elif now in ['10:45', '01:30']:
              task = 'exercise'
          else:
              task = 'unknown'

          # 建立提醒語句（示意版）
          reminders = {
              "brush": {
                  "gentle": [
                      "開始一天之前，先讓口氣也醒來 ✦",
                      "出門之前的儀式：來～去刷個牙吧！",
                      "讓嘴巴清爽一點，才有心情開始今天的事 ✧",
                      "精神恢復之前，先把牙齒清乾淨 ♡",
                      "睡飽飽後來點泡沫，感覺會很清新～",
                      "早上清爽的第一步，就是刷牙",
                      "牙齒清乾淨，心情也比較輕盈～",
                      "幫自己開啟清潔模式吧 ✦",
                      "別忘了幫口氣也準備好今天的冒險",
                      "清潔的起點，是今天的第一個小照顧"
                  ],
                  "neutral": [
                      "早晚刷牙，讓自己維持清新節奏 ✧",
                      "不管今天怎麼樣，口氣乾淨先拿到",
                      "去刷個牙再開始你要做的事吧！",
                      "口腔清潔完就可以進入下一段行程 ✨",
                      "花一點點時間清潔，也是在照顧自己",
                      "穩穩的生活習慣，從牙刷開始 ♡",
                      "給自己一點節奏，從牙齒開始清理",
                      "這是一個讓自己回到軌道的小動作",
                      "刷牙是一種整理，也是種重新出發"
                  ],
                  "concerned": [
                      "情緒跟不上也沒關係，刷牙當作切換模式",
                      "即使累也讓口腔舒服一點，自己會比較放鬆",
                      "這時候先照顧好口腔，會幫助你慢慢醒來",
                      "累的時候就從最小的行動開始，像是刷牙",
                      "你可以照自己的節奏刷牙，不急",
                      "刷牙是一個不需要決定太多的安靜小事",
                      "把注意力放在泡沫和水流，給自己一點喘息",
                      "這是屬於你自己的照顧時間",
                      "讓這幾分鐘單純一點，只刷牙就好"
                  ]
              },
              "exercise": {
                  "gentle": [
                      "今天不用多，三分鐘踏步也夠意思 ✦",
                      "你不需要做太多，三分鐘的踏步機就好 ✧",
                      "小步也能走出節奏，上踏步機動一下吧～",
                      "就當幫自己啟動身體，只要三分鐘也好",
                      "從踏步機慢慢踩起來，不用追求厲害 ✦",
                      "簡單踩幾分鐘，身體會回應你 ✨",
                      "當成活動小儀式也行～只要你願意站上去",
                      "今天也給身體一點回應，踏步機上見 ♡",
                      "走一小段，給身體一點提示也不錯",
                      "輕輕踩一下，不用負擔，也能啟動一點能量"
                  ],
                  "neutral": [
                      "今天是運動時間，記得上踏步機踩一下 ✦",
                      "準備開始動一動囉～三分鐘就好沒壓力",
                      "你可以做到的，來～走起來吧",
                      "有踏步機在，不如利用一下踩一波 ✧",
                      "每天一點點，也能累積出健康✨",
                      "運動日到了～讓踏步機幫你出個力",
                      "即使只有三分鐘，身體也會記得你的努力",
                      "幫自己踩個節奏，輕鬆不費力 ♫",
                      "你願意開始，就已經是好事"
                  ],
                  "concerned": [
                      "三分鐘可以嗎？只是簡單讓身體動起來",
                      "你狀況不一定好，但踏步機會陪你慢慢來",
                      "連續不動會讓人更累，我們就從機器開始",
                      "即使身體很重，踩幾下也算照顧自己",
                      "你不需要拼，只要願意站上去，就是行動",
                      "不是訓練，只是讓身體知道你還在乎他",
                      "動不了也沒關係，我們只做這一小段就停",
                      "三分鐘是你能掌握的小步伐",
                      "願意開始動一下，就很值得肯定",
                      "今天也能有屬於自己的節奏，從踏步機開始"
                  ]
              }
          }

          import random
          options = reminders.get(task, {}).get(tone_type, [])
          if options:
              print('\n--- 今日提醒 ---')
              print(random.choice(options))
          else:
              print('⚠️ 無對應提醒語句')
          EOF
          python3 script.py
