name: Test Script

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Generate test script
        run: |
          cat <<EOF > test.py
print("✅ 成功產生並執行 Python 腳本")
EOF
          python3 test.py
